repos:
- repo: git://github.com/pre-commit/mirrors-isort
  sha: 'v4.3.3'
  hooks:
  - id: isort
    args:
      - --check-only
      - --recursive
      - --settings-path
      - ./setup.cfg
      - .
- repo: local
  hooks:
  - id: eslint
    name: eslint
    language: system
    entry: sh -c 'npm run eslint'
    files: .js$
- repo: local
  hooks:
  - id: stylelint
    name: stylelint
    language: system
    entry: sh -c 'npm run stylelint'
    files: .css$
